# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: mySkillet
# label used for menu selection
label: byron_skillet_label
description: HA

# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panos
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - byroncollection

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
variables:
  - name: byrontest
    description: labtest
    default: byronfirewall
    type_hint: text
  - name: hostname
    description: Firewall hostname
    default: myFirewall
    type_hint: text
  - name: choices
    description: sample dropdown list
    default: choices
    type_hint: dropdown
    dd_list:
      - key: option1
        value: option1
      - key: option2
        value: option2
# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
  - name: tagname
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/tag
    file: tag.xml
- name: edlname
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/external-list"></request>
    file: edl.xml
- name: rulebasename
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase"></request>
EOF
    file: rulebase.xml
# ---------------------------------------------------------------------
# end of snippets section


